# Generated by Django 3.2 on 2021-07-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_auto_20210608_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateclass',
            name='desc',
            field=models.CharField(default='somethong', max_length=100),
        ),
        migrations.AlterField(
            model_name='templateclass',
            name='template_file',
            field=models.FileField(upload_to='template_folder/'),
        ),
    ]
