# Generated by Django 3.2 on 2021-07-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_auto_20210703_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateclass',
            name='desc',
            field=models.CharField(max_length=100),
        ),
    ]
