# Generated by Django 3.2 on 2021-07-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_rename_student_reportformatstudent_uploaded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportformatstudent',
            old_name='uploaded_by',
            new_name='uploader',
        ),
    ]
