# Generated by Django 3.2 on 2021-08-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0009_rename_uploader_reportformatstudent_uploaded_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportformatstudent',
            options={'verbose_name': 'Uploaded Report Format'},
        ),
        migrations.AlterModelOptions(
            name='templateclass',
            options={'verbose_name': 'Template'},
        ),
    ]
