# Generated by Django 3.2 on 2021-08-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0010_auto_20210804_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportFormatStudent',
        ),
    ]
