# Generated by Django 3.2 on 2021-08-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0011_delete_reportformatstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='template_file',
            field=models.FileField(default=2, upload_to='template_folder/'),
            preserve_default=False,
        ),
    ]
