# Generated by Django 3.2 on 2021-08-08 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0012_report_template_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='template',
        ),
    ]
